# Generated by Django 4.1.1 on 2023-11-25 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('product_slug', models.SlugField(max_length=255)),
                ('product_image', models.TextField(blank=True, max_length=100, verbose_name='Image')),
                ('product_description', models.TextField(blank=True, verbose_name='Description')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('product_is_aviable', models.BooleanField(default=True, verbose_name='Availability')),
                ('product_created', models.DateTimeField(blank=True, editable=False)),
                ('product_updated', models.DateTimeField(blank=True, editable=False)),
                ('characteristics', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webshop.category', verbose_name='Choose a category')),
            ],
            options={
                'verbose_name': 'historical Product',
                'verbose_name_plural': 'historical Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
